### ISSUE TITLE
Ability to add certain actions to the combat screen

### ISSUE THREAD

**Issue by Murph2** [LluisFelip/RandomAdventureRoguelike2PoolOfIdeas#13]
For instance, it can get complicated once you have multiple spells to scroll and find them, I suggest a way to lock certain actions to the combat screen so you can press one button and use that spell.

For example, locking the heal spell to the main screen next to attack, so you can heal with one oush of a button instead of pressing spells and then searching for it, saving alot of time.

![Screenshot_20200101-172620_RAR II](https://user-images.githubusercontent.com/51838690/71646920-4fa66480-2cbc-11ea-8e63-6d2603e59b8b.jpg)

**Comment by Rotpa** [comment]
Like ability slots? That's convenient

**Comment by MrDaGrover** [comment]
I've wanted something like this for a LOOOOONNNNGGG time!  These slots could be unlockable via a skill (we know Archison loves those 😉 ).  I'd love to see spells, skills, pet skills, or items be options for the "hotkey" option suggested here.

Personally I'd love to have a hotkey option on the main screen as well.  It could be useful for healing spells or eating food you've thrown in your pack for the explore.
