### ISSUE TITLE
[BUG] Food Craft Various Broken

### ISSUE THREAD

**Issue by MrDaGrover** [LluisFelip/RandomAdventureRoguelike2PoolOfIdeas#22]
**Describe the bug**
"Craft Various" sites not work for any food items. It says success, but the items are not in your inventory.

**To Reproduce**
1. Go to 'Crafting'
2. Click on 'Craft Various' for any food item.
3. Type in amount to craft
4. Hit craft
5. See success toast
6. Go to inventory and try and locate the crafted food items :frowning_face: 

**Expected behavior**
I excited to have the number of food items I created in my inventory.

**Screenshots**
Not necessary. Simple issue.

**Smartphone (please complete the following information):**
 - Device: Gravity S8
 - Android Version 9

**Additional context**
Other craft various seem to be working fine.

**Comment by LluisFelip** [comment]
Will upload the fix later today or tomorrow with a few more fixes :)

Thanks @MrDaGrover !
