### ISSUE TITLE
Attributes boosting for skill points[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Palendalaar28** [LluisFelip/RandomAdventureRoguelike2PoolOfIdeas#23]
I think about boosting stats for skill points. For Example  ATK+/DEF+/SPD+/INT+/ and you gain +10 . That's cost will be about 10SP. 
It Will be cool if HP+/MP+/HNR+ give +25 for about 10 SP or something like that.

**Comment by LluisFelip** [comment]
Hey!

It's duplicated, there's already an issue with this idea: #9
