### ISSUE TITLE
[BUG] Screen Doesn't Reset to Main Attack Screen After Casting Spell

### ISSUE THREAD

**Issue by MrDaGrover** [LluisFelip/RandomAdventureRoguelike2PoolOfIdeas#24]
**Describe the bug**
After Casting a spell in battle by selecting a spell frim the spell list, the screen does not reset back to the main battle screen if the spell doesn't kill the monster. The spell is still cast, and the monster does their counter action, but you have to manually get back to the main attack screen by swiping down. Not sure if this is specific to the beta version (0.7.3341) or not.

**To Reproduce**
1. Attack a monster
2. Click on Spells
3. Cast a spell that won't kill the monster like Ice Armor or Calm Monster.
4. Observe the vibration that you took damage, but the screen is still on the spell casting screen and you have no idea the result of your spell.

**Expected behavior**
After casting a spell it returns you back to the main attack interface to see the results, the monster's counter, and decide the next move.

**Screenshots**
Not sure screenshots would be super helpful in illustrating this.

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - Android Version: 9

**Additional context**
This was in beta version 0.7.3341

**Comment by LluisFelip** [comment]
Thanks for reporting this! <3

Fixed!
