### ISSUE TITLE
[FEATURE REQUEST] A new starting advantage, Librarian!

### ISSUE THREAD

**Issue by CharmandertheEPIC** [LluisFelip/RandomAdventureRoguelike2PoolOfIdeas#29]
The librarian spends all day near books, shouldn't they know some more than others? The librarian is a new role similar to warrior or cleric. This role is provided with an experience potion, 5-ish skill points, and one crafting recipe. This role may seem overpowered, but these items aren't too powerful. The most powerful advantage the librarian has, is the skill points. There are 5 because only one passive skill can be unlocked with 5 points. Overall, this is a good occupation to use with the unknown race if you like the extra skill points, it's lore-friendly, and not too op!

**Comment by LluisFelip** [comment]
Great idea!

Will come in the next update ;)
