### ISSUE TITLE
Buffing Weapon Experience Gain

### ISSUE THREAD

**Issue by TheError007** [LluisFelip/RandomAdventureRoguelike2PoolOfIdeas#8]
**A short explanation of your idea**
It will be better to buff skill/experience gain for weapons.
**Describe your idea**
This would help you to get weapon skills faster, not after 200+ fights.

**Additional context**
Currently mastering all weapons is pain in the butt.

**Comment by LluisFelip** [comment]
In the next update there will be a new skill called "Weapon Learner" which will allow to increase the experience gained when attacking :)
