### ISSUE TITLE
Ability Points from Skill Points

### ISSUE THREAD

**Issue by TheError007** [LluisFelip/RandomAdventureRoguelike2PoolOfIdeas#9]
**A short explanation of your idea**
Adding Ability points, which you could assign to your stats.

**Describe your idea**
You could get them by spending your Skill Points: 1 Skill Point = 2 Ability Points.

**Additional context**
You would unlock this after obtaining all of the learnable skills.

**Comment by LluisFelip** [comment]
I forgot to close this issue, it was implemented in the 1.0 update :)
